/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef __SCX_SNAKE_INTF_H
#define __SCX_SNAKE_INTF_H

#ifndef __VMLINUX_H__
typedef unsigned char	   u8;
typedef unsigned int	   u32;
typedef unsigned long long u64;
#endif

#define SNAKE_ABI_VERSION 33
#define SNAKE_MAX_RUNGS 17
#define SNAKE_EXPANDED_MITOSIS_RUNGS 16
#define SNAKE_MAX_GENERIC_RUNGS 9
#define SNAKE_MAX_QUEUE_RUNGS 8
#define SNAKE_LADDER_SLOTS 2
#define SNAKE_LADDER_SLOT_INVALID SNAKE_LADDER_SLOTS
#define SNAKE_MAX_CPUS 1024
#define SNAKE_MASK_BYTES (SNAKE_MAX_CPUS / 8)
#define SNAKE_MAX_MASK_TABLES 4
#define SNAKE_MAX_QUEUE_CELLS 256
#define SNAKE_MAX_CELL_LLCS 32
#define SNAKE_MAX_NORMAL_QUEUES 8192
#define SNAKE_QUEUE_MODE_NONE 0U
#define SNAKE_QUEUE_MODE_GLOBAL 1U
#define SNAKE_QUEUE_MODE_CELL 2U
#define SNAKE_AFFINITY_DSQ_BASE 0x10000000ULL
#define SNAKE_NORMAL_DSQ_BASE 0x20000000ULL
#define SNAKE_QUEUE_CLASS_NORMAL 0U
#define SNAKE_QUEUE_CLASS_AFFINITY 1U
#define SNAKE_QUEUE_CLASS_FAIRNESS 2U
#define SNAKE_QUEUE_CELL_NONE 0xffffffffU
#define SNAKE_QUEUE_CPU_NONE 0xffffffffU
#define SNAKE_RUNG_F_INTERSECT_TASK_ALLOWED (1U << 0)
#define SNAKE_RUNG_F_PICK_IDLE_CORE (1U << 1)
#define SNAKE_RUNG_F_PICK_RANDOM (1U << 2)
#define SNAKE_QUEUE_RUNG_F_DIRECT_DISPATCH (1U << 0)
#define SNAKE_EEVDF_SLICE_NS 5000000ULL
#define SNAKE_EEVDF_PROMOTE_BATCH 64
#define SNAKE_EEVDF_ELIGIBLE_DSQ 0
#define SNAKE_EEVDF_FUTURE_DSQ 1
#define SNAKE_VTIME_GLOBAL_DSQ 2ULL
#define SNAKE_VTIME_CPU_DSQ_BASE 3ULL
#define SNAKE_FIFO_DSQ 0x30000000ULL
#define SNAKE_VTIME_SLICE_NS 5000000ULL
#define SNAKE_VTIME_MIN_SLICE_NS 1000000ULL
#define SNAKE_BASE_WEIGHT 100
#define SNAKE_TASK_CELL_F_MANUAL (1U << 0)
#define SNAKE_TASK_CELL_F_MANAGED (1U << 1)
#define SNAKE_CALLBACK_TIMING_BUCKETS 64
#define SNAKE_FINE_TIMING_BUCKETS 32
#define SNAKE_FINE_TIMING_SELECT_CPU (1U << 0)
#define SNAKE_FINE_TIMING_ENQUEUE (1U << 1)
#define SNAKE_FINE_TIMING_DISPATCH (1U << 2)
#define SNAKE_FINE_TIMING_RUNNABLE (1U << 3)
#define SNAKE_FINE_TIMING_RUNNING (1U << 4)
#define SNAKE_FINE_TIMING_STOPPING (1U << 5)
#define SNAKE_FINE_TIMING_QUIESCENT (1U << 6)

enum snake_fairness_mode {
	SNAKE_FAIRNESS_INVALID = 0,
	SNAKE_FAIRNESS_FIFO    = 1,
	SNAKE_FAIRNESS_EEVDF   = 2,
	SNAKE_FAIRNESS_VTIME   = 3,
};

enum snake_callback {
	SNAKE_CALLBACK_SELECT_CPU = 0,
	SNAKE_CALLBACK_ENQUEUE,
	SNAKE_CALLBACK_DISPATCH,
	SNAKE_CALLBACK_RUNNABLE,
	SNAKE_CALLBACK_RUNNING,
	SNAKE_CALLBACK_STOPPING,
	SNAKE_CALLBACK_QUIESCENT,
	SNAKE_NR_CALLBACKS,
};

struct snake_callback_timing {
	u64 total_ns;
	u64 buckets[SNAKE_CALLBACK_TIMING_BUCKETS];
};

enum snake_rung_ladder {
	SNAKE_RUNG_LADDER_IDLE = 0,
	SNAKE_RUNG_LADDER_ENQUEUE,
	SNAKE_RUNG_LADDER_DISPATCH,
	SNAKE_NR_RUNG_LADDERS,
};

struct snake_rung_timing_event {
	u64 generation;
	u64 elapsed_ns;
	u32 ladder;
	u32 rung;
};

enum snake_fine_timing_callback {
	SNAKE_FINE_TIMING_CALLBACK_SELECT_CPU = 0,
	SNAKE_FINE_TIMING_CALLBACK_ENQUEUE,
	SNAKE_FINE_TIMING_CALLBACK_DISPATCH,
	SNAKE_FINE_TIMING_CALLBACK_RUNNABLE,
	SNAKE_FINE_TIMING_CALLBACK_RUNNING,
	SNAKE_FINE_TIMING_CALLBACK_STOPPING,
	SNAKE_FINE_TIMING_CALLBACK_QUIESCENT,
	SNAKE_NR_FINE_TIMING_CALLBACKS,
};

enum snake_fine_timing_stage {
	SNAKE_FINE_TIMING_SELECT_ACQUIRE_LADDER = 0,
	SNAKE_FINE_TIMING_SELECT_POLICY_LADDER,
	SNAKE_FINE_TIMING_SELECT_QUEUE_TARGET,
	SNAKE_FINE_TIMING_SELECT_DIRECT_INSERT,
	SNAKE_FINE_TIMING_SELECT_STRICT_PREEMPT,
	SNAKE_FINE_TIMING_SELECT_FALLBACK,
	SNAKE_FINE_TIMING_SELECT_CELL_CLOCK_READ,
	SNAKE_FINE_TIMING_SELECT_FINISH,
	SNAKE_FINE_TIMING_ENQUEUE_ACQUIRE_LADDER,
	SNAKE_FINE_TIMING_ENQUEUE_CANCEL_DIRECT,
	SNAKE_FINE_TIMING_ENQUEUE_PREPARE_RUNNABLE,
	SNAKE_FINE_TIMING_ENQUEUE_PREPARE_ROUTE_LOOKUP,
	SNAKE_FINE_TIMING_ENQUEUE_PREPARE_TASK_STORAGE,
	SNAKE_FINE_TIMING_ENQUEUE_PREPARE_CELL_CLOCK,
	SNAKE_FINE_TIMING_ENQUEUE_PREPARE_CREDIT_CLAMP,
	SNAKE_FINE_TIMING_ENQUEUE_CELL_CLOCK_READ,
	SNAKE_FINE_TIMING_ENQUEUE_CELL_VALIDATE,
	SNAKE_FINE_TIMING_ENQUEUE_PICK_TARGET,
	SNAKE_FINE_TIMING_ENQUEUE_NORMAL_DSQ_INSERT,
	SNAKE_FINE_TIMING_ENQUEUE_NORMAL_ACCOUNT_KICK,
	SNAKE_FINE_TIMING_ENQUEUE_AFFINITY_DSQ_INSERT,
	SNAKE_FINE_TIMING_ENQUEUE_AFFINITY_PATH,
	SNAKE_FINE_TIMING_ENQUEUE_FINISH,
	SNAKE_FINE_TIMING_DISPATCH_ACQUIRE_LADDER,
	SNAKE_FINE_TIMING_DISPATCH_ROUTE_LOOKUP,
	SNAKE_FINE_TIMING_DISPATCH_LOCAL_DSQ_CHECK,
	SNAKE_FINE_TIMING_DISPATCH_STATE_LOOKUP,
	SNAKE_FINE_TIMING_DISPATCH_NORMAL_HEAD_PEEK,
	SNAKE_FINE_TIMING_DISPATCH_REMOTE_SCAN_1_QUEUE,
	SNAKE_FINE_TIMING_DISPATCH_REMOTE_SCAN_2_4_QUEUES,
	SNAKE_FINE_TIMING_DISPATCH_REMOTE_SCAN_5_8_QUEUES,
	SNAKE_FINE_TIMING_DISPATCH_REMOTE_SCAN_9_PLUS_QUEUES,
	SNAKE_FINE_TIMING_DISPATCH_AFFINITY_HEAD_PEEK,
	SNAKE_FINE_TIMING_DISPATCH_ARBITRATE,
	SNAKE_FINE_TIMING_DISPATCH_KEEP_RUNNING,
	SNAKE_FINE_TIMING_DISPATCH_MOVE_TO_LOCAL,
	SNAKE_FINE_TIMING_DISPATCH_MOVE_NORMAL_SUCCESS,
	SNAKE_FINE_TIMING_DISPATCH_MOVE_NORMAL_MISS,
	SNAKE_FINE_TIMING_DISPATCH_MOVE_AFFINITY_SUCCESS,
	SNAKE_FINE_TIMING_DISPATCH_MOVE_AFFINITY_MISS,
	SNAKE_FINE_TIMING_DISPATCH_REPLENISH,
	SNAKE_FINE_TIMING_DISPATCH_FINISH,
	SNAKE_FINE_TIMING_RUNNABLE_ACQUIRE_LADDER,
	SNAKE_FINE_TIMING_RUNNABLE_RUNNABLE_STATE,
	SNAKE_FINE_TIMING_RUNNABLE_CELL_CLOCK_READ,
	SNAKE_FINE_TIMING_RUNNABLE_FINISH,
	SNAKE_FINE_TIMING_RUNNING_ACQUIRE_LADDER,
	SNAKE_FINE_TIMING_RUNNING_MEMBERSHIP_ACCOUNT,
	SNAKE_FINE_TIMING_RUNNING_RUN_STATE,
	SNAKE_FINE_TIMING_RUNNING_CELL_CLOCK_READ,
	SNAKE_FINE_TIMING_RUNNING_CELL_CLOCK_RUN_START_ADVANCE,
	SNAKE_FINE_TIMING_RUNNING_CELL_CLOCK_RUN_START_NOOP,
	SNAKE_FINE_TIMING_RUNNING_AFFINITY_CLOCK_ADVANCE,
	SNAKE_FINE_TIMING_RUNNING_AFFINITY_CLOCK_NOOP,
	SNAKE_FINE_TIMING_RUNNING_FINISH,
	SNAKE_FINE_TIMING_STOPPING_ACQUIRE_LADDER,
	SNAKE_FINE_TIMING_STOPPING_RUN_STATE,
	SNAKE_FINE_TIMING_STOPPING_RUNTIME_STAT,
	SNAKE_FINE_TIMING_STOPPING_FINISH,
	SNAKE_FINE_TIMING_QUIESCENT_ACQUIRE_LADDER,
	SNAKE_FINE_TIMING_QUIESCENT_QUEUE_TIMING_CANCEL,
	SNAKE_FINE_TIMING_QUIESCENT_DIRECT_CANCEL,
	SNAKE_FINE_TIMING_QUIESCENT_FAIRNESS_STATE,
	SNAKE_FINE_TIMING_QUIESCENT_FINISH,
	SNAKE_NR_FINE_TIMING_STAGES,
};

enum snake_dsq_operation {
	SNAKE_DSQ_OP_NONE = 0,
	SNAKE_DSQ_OP_INSERT,
	SNAKE_DSQ_OP_MOVE,
	SNAKE_DSQ_OP_MOVE_TO_LOCAL,
	SNAKE_DSQ_OP_REMOVE,
	SNAKE_DSQ_OP_TRANSFER,
};

enum snake_dsq_outcome {
	SNAKE_DSQ_OUTCOME_NONE = 0,
	SNAKE_DSQ_OUTCOME_SUCCESS,
	SNAKE_DSQ_OUTCOME_MISS,
	SNAKE_DSQ_OUTCOME_ERROR,
};

struct snake_fine_timing_config {
	u64 session_ids[SNAKE_NR_FINE_TIMING_CALLBACKS];
	u32 enabled_mask;
	u32 reserved;
};

struct snake_fine_timing_event {
	u64 session_id;
	u64 elapsed_ns;
	u64 source_dsq_id;
	u64 target_dsq_id;
	u32 stage;
	u32 operation;
	u32 outcome;
	u32 queue_class;
};

struct snake_queue_timing_counters {
	u64 started_samples;
	u64 completed_samples;
	u64 dropped_samples;
};

struct snake_queue_timing_event {
	u64 session_id;
	u64 dsq_id;
	u64 residence_ns;
	u32 cell_index;
	u32 queue_class;
	u32 depth_after_insert;
	u32 depth_after_dispatch;
};

/* Stable operation codes shared by the userspace compiler and BPF. */
enum snake_opcode {
	SNAKE_OP_INVALID	      = 0,
	SNAKE_OP_CLAIM_IDLE	      = 1,
	SNAKE_OP_PICK_IDLE	      = 2,
	SNAKE_OP_PICK_IDLE_MASK_TABLE = 3,
	SNAKE_OP_PICK_RANDOM_IDLE     = 4,
	SNAKE_OP_KERNEL_DEFAULT	      = 5,
	SNAKE_OP_SYNC_WAKE_AFFINE     = 6,
	SNAKE_OP_PICK_IDLE_QUEUE_MASK = 7,
	SNAKE_OP_PICK_IDLE_PREFER_PREVIOUS = 8,
};

/* Exhaustion behavior applied when every select rung misses. */
enum snake_fallback {
	SNAKE_FALLBACK_INVALID	    = 0,
	SNAKE_FALLBACK_PREVIOUS_CPU = 1,
	SNAKE_FALLBACK_ANY_ALLOWED  = 2,
};

/* Topology-blind operand sources consumed by mechanical rung operations. */
enum snake_input_source {
	SNAKE_INPUT_INVALID	      = 0,
	SNAKE_INPUT_CPU_PREV	      = 1,
	SNAKE_INPUT_MASK_TASK_ALLOWED = 2,
	SNAKE_INPUT_TASK_CELL	      = 3,
	SNAKE_INPUT_QUEUE_CELL	      = 4,
	SNAKE_INPUT_TASK_ALLOWED_RESTRICTED = 5,
};

enum snake_queue_mask_kind {
	SNAKE_QUEUE_MASK_INVALID    = 0,
	SNAKE_QUEUE_MASK_PRIMARY    = 1,
	SNAKE_QUEUE_MASK_BORROWABLE = 2,
	SNAKE_QUEUE_MASK_LOCAL_LLC  = 3,
	SNAKE_QUEUE_MASK_GROUP_LLC  = 4,
};

enum snake_enqueue_opcode {
	SNAKE_ENQUEUE_OP_INVALID  = 0,
	SNAKE_ENQUEUE_OP_CELL     = 1,
	SNAKE_ENQUEUE_OP_AFFINITY = 2,
	SNAKE_ENQUEUE_OP_TRY_INSERT = 3,
	SNAKE_ENQUEUE_OP_INSERT     = 4,
	SNAKE_ENQUEUE_OP_TRY_DIRECT = 5,
	SNAKE_ENQUEUE_OP_INSERT_CPU = 6,
};

enum snake_dispatch_opcode {
	SNAKE_DISPATCH_OP_INVALID  = 0,
	SNAKE_DISPATCH_OP_CELL     = 1,
	SNAKE_DISPATCH_OP_AFFINITY = 2,
	SNAKE_DISPATCH_OP_MIN_VTIME = 3,
	SNAKE_DISPATCH_OP_PEEK       = 4,
	SNAKE_DISPATCH_OP_CONSUME    = 5,
	SNAKE_DISPATCH_OP_DRAIN      = 6,
	SNAKE_DISPATCH_OP_STEAL      = 7,
};

enum snake_queue_input {
	SNAKE_QUEUE_INPUT_INVALID = 0,
	SNAKE_QUEUE_INPUT_CPU,
	SNAKE_QUEUE_INPUT_LOCAL,
	SNAKE_QUEUE_INPUT_REMOTE,
	SNAKE_QUEUE_INPUT_CELL,
	SNAKE_QUEUE_INPUT_MIN_VTIME,
	SNAKE_QUEUE_INPUT_CELL_ORPHAN,
	SNAKE_QUEUE_INPUT_CELL_SIBLING,
	SNAKE_QUEUE_INPUT_GROUP_LLC,
};

enum snake_dispatch_fallback {
	SNAKE_DISPATCH_FALLBACK_INVALID = 0,
	SNAKE_DISPATCH_FALLBACK_CPU,
	SNAKE_DISPATCH_FALLBACK_LOCAL,
	SNAKE_DISPATCH_FALLBACK_REMOTE,
	SNAKE_DISPATCH_FALLBACK_CELL_SIBLING,
};

#define SNAKE_DISPATCH_FALLBACK_BITS 8U
#define SNAKE_DISPATCH_FALLBACK_MASK 0xffULL
#define SNAKE_DISPATCH_FALLBACK_MAX 3U

/* Userspace annotation attached to one thread through BPF task storage. */
struct snake_task_cell {
	u32 cell_id;
	u32 cell_epoch;
	u32 needs_rehome;
	u32 managed_cell_id;
	u32 managed_cell_epoch;
	u32 flags;
	u64 llc_group_id;
	u32 llc_group_generation;
	u32 reserved;
};

/* Serialized userspace CPU mask stored in immutable queue descriptors. */
struct snake_mask_data {
	u32 valid;
	u8  bits[SNAKE_MASK_BYTES];
};

struct snake_queue_header {
	u32 mode;
	u32 nr_cells;
	u32 nr_normal_queues;
	u32 nr_normal_dsqs;
	u32 nr_cpus;
	u64 topology_generation;
};

struct snake_queue_cell {
	u32 valid;
	u32 external_id;
	u32 cpu_weight;
	u32 clock_index;
	u32 first_normal_queue;
	u32 nr_normal_queues;
	u32 slot_epoch;
	u32 reserved;
	struct snake_mask_data primary;
	struct snake_mask_data borrowable;
};

struct snake_normal_queue {
	u32 valid;
	u32 cell_index;
	u32 clock_index;
	u32 consumer_cpu;
	u32 reserved[4];
	struct snake_mask_data consumers;
};

struct snake_cpu_queue {
	u32 valid;
	u32 owner_cell_index;
	u32 normal_queue_index;
	u32 reserved;
};

enum snake_cell_stat {
	SNAKE_CELL_STAT_RUNTIME_NS = 0,
	SNAKE_CELL_STAT_PRIMARY_RUNTIME_NS,
	SNAKE_CELL_STAT_BORROWED_RUNTIME_NS,
	SNAKE_CELL_STAT_LENT_RUNTIME_NS,
	SNAKE_CELL_STAT_NORMAL_ENQUEUES,
	SNAKE_CELL_STAT_AFFINITY_ENQUEUES,
	SNAKE_CELL_STAT_NORMAL_DISPATCHES,
	SNAKE_CELL_STAT_AFFINITY_DISPATCHES,
	SNAKE_CELL_STAT_CLOCK_TRANSITIONS,
	SNAKE_CELL_STAT_FOREIGN_AFFINITY_RUNTIME_NS,
	SNAKE_CELL_STAT_GROUP_RUNTIME_NS,
	SNAKE_CELL_STAT_GROUP_PREFERRED_RUNTIME_NS,
	SNAKE_CELL_STAT_GROUP_FALLBACK_RUNTIME_NS,
	SNAKE_NR_CELL_STATS,
};

/*
 * Mechanical instruction consumed by BPF. Semantic topology concepts must be
 * lowered by userspace into operand sources and data tables.
 */
struct snake_rung {
	u32 opcode;
	u32 input;
	u32 flags;
	u32 reserved;
	u64 data;
};

struct snake_queue_rung {
	u32 opcode;
	u32 input;
	u32 flags;
	u32 reserved;
	u64 data;
};

/* Complete userspace-compiled ladder installed as one runtime generation. */
struct snake_compiled_ladder {
	u64		  generation;
	u32		  policy_abi_version;
	u32		  nr_rungs;
	u32		  nr_mask_tables;
	u32		  fallback_mode;
	struct snake_rung rungs[SNAKE_MAX_RUNGS];
	u32		  nr_enqueue_rungs;
	u32		  nr_dispatch_rungs;
	struct snake_queue_rung enqueue_rungs[SNAKE_MAX_QUEUE_RUNGS];
	struct snake_queue_rung dispatch_rungs[SNAKE_MAX_QUEUE_RUNGS];
};

/* Fixed map-key layout for global and per-rung scheduler counters. */
enum snake_stat {
	SNAKE_STAT_SELECT_CALLS = 0,
	SNAKE_STAT_DISPATCH_CALLS,
	SNAKE_STAT_DIRECT_DISPATCHES,
	SNAKE_STAT_LADDER_EXHAUSTIONS,
	SNAKE_STAT_FALLBACK_PREV,
	SNAKE_STAT_FALLBACK_ANY,
	SNAKE_STAT_INVALID_ERRORS,
	SNAKE_STAT_ENQUEUES,
	SNAKE_STAT_FIFO_SHARED_ENQUEUES,
	SNAKE_STAT_FIFO_SHARED_DISPATCHES,
	SNAKE_STAT_RUNNING,
	SNAKE_STAT_MEMBERSHIP_NO_CELL_RUNS,
	SNAKE_STAT_MEMBERSHIP_INVALID_RUNS,
	SNAKE_STAT_STOPPING,
	SNAKE_STAT_QUIESCENT,
	SNAKE_STAT_RUNTIME_NS,
	SNAKE_STAT_SELECT_LATENCY_NS,
	SNAKE_STAT_SELECT_LATENCY_MAX_NS,
	SNAKE_STAT_CELL_REHOMES,
	SNAKE_STAT_CELL_REHOME_MISSES,
	SNAKE_STAT_QUEUE_REHOME_PREEMPTIONS,
	SNAKE_STAT_QUEUE_STALE_REHOME_RUNS,
	SNAKE_STAT_QUEUE_BORROW_YIELDS,
	SNAKE_STAT_SLICE_SHRINK_MIN,
	SNAKE_STAT_SLICE_SHRINK_PROPORTIONAL,
	SNAKE_STAT_SLICE_SHRINK_MAX,
	SNAKE_STAT_VTIME_ENQUEUES,
	SNAKE_STAT_VTIME_DISPATCHES,
	SNAKE_STAT_VTIME_CPU_ENQUEUES,
	SNAKE_STAT_VTIME_CPU_DISPATCHES,
	SNAKE_STAT_VTIME_STRICT_PREEMPT_QUEUES,
	SNAKE_STAT_VTIME_DIRECT_RUNTIME_NS,
	SNAKE_STAT_VTIME_QUEUED_RUNTIME_NS,
	SNAKE_STAT_VTIME_CREDIT_CLAMPS,
	SNAKE_STAT_VTIME_ACCOUNTING_ERRORS,
	SNAKE_STAT_VTIME_EQUAL_HEAD_TIES,
	SNAKE_STAT_EEVDF_ELIGIBLE_ENQUEUES,
	SNAKE_STAT_EEVDF_FUTURE_ENQUEUES,
	SNAKE_STAT_EEVDF_PROMOTIONS,
	SNAKE_STAT_EEVDF_FORCED_ADVANCES,
	SNAKE_STAT_EEVDF_DISPATCHES,
	SNAKE_STAT_EEVDF_STRICT_PREEMPT_QUEUES,
	SNAKE_STAT_EEVDF_DIRECT_RUNTIME_NS,
	SNAKE_STAT_EEVDF_QUEUED_RUNTIME_NS,
	SNAKE_STAT_EEVDF_LAG_CLAMPS,
	SNAKE_STAT_EEVDF_RUN_LAG_CLAMPS,
	SNAKE_STAT_EEVDF_ACCOUNTING_ERRORS,
	SNAKE_STAT_GLOBAL_NR,
	SNAKE_STAT_RUNG_ATTEMPT_BASE = SNAKE_STAT_GLOBAL_NR,
	SNAKE_STAT_RUNG_HIT_BASE =
		SNAKE_STAT_RUNG_ATTEMPT_BASE + SNAKE_MAX_RUNGS,
	SNAKE_STAT_RUNG_MISS_BASE = SNAKE_STAT_RUNG_HIT_BASE + SNAKE_MAX_RUNGS,
	SNAKE_STAT_RUNG_ERROR_BASE =
		SNAKE_STAT_RUNG_MISS_BASE + SNAKE_MAX_RUNGS,
	SNAKE_STAT_ENQUEUE_RUNG_ATTEMPT_BASE =
		SNAKE_STAT_RUNG_ERROR_BASE + SNAKE_MAX_RUNGS,
	SNAKE_STAT_ENQUEUE_RUNG_HIT_BASE =
		SNAKE_STAT_ENQUEUE_RUNG_ATTEMPT_BASE + SNAKE_MAX_QUEUE_RUNGS,
	SNAKE_STAT_ENQUEUE_RUNG_MISS_BASE =
		SNAKE_STAT_ENQUEUE_RUNG_HIT_BASE + SNAKE_MAX_QUEUE_RUNGS,
	SNAKE_STAT_ENQUEUE_RUNG_ERROR_BASE =
		SNAKE_STAT_ENQUEUE_RUNG_MISS_BASE + SNAKE_MAX_QUEUE_RUNGS,
	SNAKE_STAT_DISPATCH_RUNG_ATTEMPT_BASE =
		SNAKE_STAT_ENQUEUE_RUNG_ERROR_BASE + SNAKE_MAX_QUEUE_RUNGS,
	SNAKE_STAT_DISPATCH_RUNG_HIT_BASE =
		SNAKE_STAT_DISPATCH_RUNG_ATTEMPT_BASE + SNAKE_MAX_QUEUE_RUNGS,
	SNAKE_STAT_DISPATCH_RUNG_MISS_BASE =
		SNAKE_STAT_DISPATCH_RUNG_HIT_BASE + SNAKE_MAX_QUEUE_RUNGS,
	SNAKE_STAT_DISPATCH_RUNG_ERROR_BASE =
		SNAKE_STAT_DISPATCH_RUNG_MISS_BASE + SNAKE_MAX_QUEUE_RUNGS,
	SNAKE_STAT_DISPATCH_RUNG_SELECTED_BASE =
		SNAKE_STAT_DISPATCH_RUNG_ERROR_BASE + SNAKE_MAX_QUEUE_RUNGS,
	SNAKE_STAT_DISPATCH_RUNG_MOVE_MISS_BASE =
		SNAKE_STAT_DISPATCH_RUNG_SELECTED_BASE + SNAKE_MAX_QUEUE_RUNGS,
	SNAKE_STAT_DISPATCH_RUNG_FALLBACK_ATTEMPT_BASE =
		SNAKE_STAT_DISPATCH_RUNG_MOVE_MISS_BASE + SNAKE_MAX_QUEUE_RUNGS,
	SNAKE_STAT_DISPATCH_RUNG_FALLBACK_HIT_BASE =
		SNAKE_STAT_DISPATCH_RUNG_FALLBACK_ATTEMPT_BASE + SNAKE_MAX_QUEUE_RUNGS,
	SNAKE_STAT_DISPATCH_RUNG_FALLBACK_MISS_BASE =
		SNAKE_STAT_DISPATCH_RUNG_FALLBACK_HIT_BASE + SNAKE_MAX_QUEUE_RUNGS,
	SNAKE_STAT_VTIME_CLOCK_CAS_RETRIES =
		SNAKE_STAT_DISPATCH_RUNG_FALLBACK_MISS_BASE + SNAKE_MAX_QUEUE_RUNGS,
	SNAKE_STAT_VTIME_CLOCK_CAS_EXHAUSTIONS,
	SNAKE_NR_STATS,
};

#endif /* __SCX_SNAKE_INTF_H */
